baseURL = 'https://innovation.3dbag.nl/'
languageCode = 'nl-nl'
title = '3DBAG Innovation Platform'
theme = 'PaperMod'

[params.profileMode]
enabled = true
title = "Binnenkort beschikbaar" # optional default will be site title
subtitle = "Informatie over het 3DBAG innovation platform"
# imageUrl = "<image link>" # optional
# imageTitle = "<title of image as alt>" # optional
# imageWidth = 120 # custom size
# imageHeight = 120 # custom size
