baseURL = 'https://innovation.3dbag.nl/'
languageCode = 'nl-nl'
title = '3DBAG Innovatie Platform'
theme = 'PaperMod'

[params.profileMode]
enabled = true
title = "3D BAG Innovatieplatform (Binnenkort beschikbaar...)"
subtitle = "Dit is de website van het 3DBAG innovatieplatform. Dit platform wordt gecoördineerd door Geonovum. Op deze website wordt een uitleg gegeven van het platform en worden activiteiten, resultaten etc van het platform gepubliceerd. "
imageUrl = "./images/tud.jpg"
imageWidth = 400  
imageHeight = 400 

[[params.profileMode.buttons]]
name = "About"
url = "/about"

[[params.profileMode.buttons]]
name = "Publicaties"
url = "/publicaties"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/3DBAG"
